apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: ping-pong-count
          persistentVolumeClaim:
            claimName: ping-pong-claim
        - name: shared-text
          emptyDir: {}
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-text
              mountPath: /usr/src/app/files
            - name: ping-pong-count
              mountPath: /usr/src/app/count
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-text
              mountPath: /usr/src/app/files